### ISSUE TITLE
Support meta-attribute ili2db.mapping for structures

### ISSUE THREAD

**Issue by gacarrillor** [AgenciaImplementacion/umleditor#3]
Structures should (optionally) support the meta-attribute `ili2db.mapping` whose values can be either `MultiLine` or `MultiSurface` (more details in [IliMetaAttrNames.java](https://github.com/claeis/ili2db/blob/master/src/ch/ehi/ili2db/mapping/IliMetaAttrNames.java) and [ili2db.rst](https://github.com/claeis/ili2db/blob/master/docs/ili2db_es.rst)).

**Comment by Alelizzt** [comment]
Added! [Release 3.6.3.4](https://github.com/AgenciaImplementacion/umleditor/releases/tag/v3.6.3.4)
